In [1]:
import pandas as pd

df = pd.read_csv("preprocessing_eda_done_v3.csv")

df.head()

,OBJECTID,PropertyID,xrCompositeLandUseID,xrBuildingTypeID,ParcelID,LocationStartNumber,StreetNameAndWay,xrPrimaryNeighborhoodID,LandSF,TotalFinishedArea,...,PrimaryGrantor,SaleDate,SalePrice,TotalAppraisedValue,LegalReference,xrSalesValidityID,xrDeedID,AssrLandUse,WasZeroPrice,LogSalePrice
0,1,8,3,6.0,121-698-063,77,STAFFORD ST,2,6000.0,1092.0,...,SCOTT NASTASSIA,2024-07-01 00:00:00+00:00,259000.0,187200,08275 0343,1,10,ONE FAMILY,False,12.464587
1,2,9,3,3.0,121-698-062,73,STAFFORD ST,2,6000.0,936.0,...,DIAZ RAFAEL,2022-04-26 00:00:00+00:00,208000.0,192300,07948-0001,1,10,ONE FAMILY,False,12.245298
2,3,12,3,6.0,144-698-066,61,STAFFORD ST,2,6000.0,1111.0,...,KERN THOMAS,2023-12-22 00:00:00+00:00,125000.0,148400,08197-0077,1,10,ONE FAMILY,False,11.736077
3,5,25,3,6.0,144-698-053,211,NEWINGTON AVE,2,5040.0,1684.0,...,BAIJANATH BISSNOW P,2021-01-11 00:00:00+00:00,177000.0,197900,07701-0245,1,10,ONE FAMILY,False,12.083911
4,7,29,3,3.0,144-698-049,18,BRISTOL ST,2,6000.0,900.0,...,CAO PHUONG,2021-09-21 00:00:00+00:00,188000.0,170700,07834-0299,1,10,ONE FAMILY,False,12.144203

In [3]:
# convert date column
df["SaleDate"] = pd.to_datetime(df["SaleDate"])

# check info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4566 entries, 0 to 4565
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   OBJECTID                 4566 non-null   int64
 1   PropertyID               4566 non-null   int64
 2   xrCompositeLandUseID     4566 non-null   int64
 3   xrBuildingTypeID         4566 non-null   float64
 4   ParcelID                 4566 non-null   str
 5   LocationStartNumber      4566 non-null   int64
 6   StreetNameAndWay         4566 non-null   str
 7   xrPrimaryNeighborhoodID  4566 non-null   int64
 8   LandSF                   4566 non-null   float64
 9   TotalFinishedArea        4566 non-null   float64
 10  LivingUnits              4566 non-null   float64
 11  OwnerLastName            4566 non-null   str
 12  PrimaryGrantor           4566 non-null   str
 13  SaleDate                 4566 non-null   datetime64[us, UTC]
 14  SalePrice                4566 non-null   float64
 15  TotalAppraisedValue      4566 non-null   int64
 16  LegalReference           4566 non-null   str
 17  xrSalesValidityID        4566 non-null   int64
 18  xrDeedID                 4566 non-null   int64
 19  AssrLandUse              4566 non-null   str
 20  WasZeroPrice             4566 non-null   bool
 21  LogSalePrice             4566 non-null   float64
dtypes: bool(1), datetime64[us, UTC](1), float64(6), int64(8), str(6)
memory usage: 1.0 MB

In [5]:
# create year and month from sale date
df["SaleYear"] = df["SaleDate"].dt.year
df["SaleMonth"] = df["SaleDate"].dt.month

# price per sqft
df["PricePerSqft"] = df["SalePrice"] / df["TotalFinishedArea"]

# appraisal ratio
df["AppraisalRatio"] = df["SalePrice"] / df["TotalAppraisedValue"]

df.head()

,OBJECTID,PropertyID,xrCompositeLandUseID,xrBuildingTypeID,ParcelID,LocationStartNumber,StreetNameAndWay,xrPrimaryNeighborhoodID,LandSF,TotalFinishedArea,...,LegalReference,xrSalesValidityID,xrDeedID,AssrLandUse,WasZeroPrice,LogSalePrice,SaleYear,SaleMonth,PricePerSqft,AppraisalRatio
0,1,8,3,6.0,121-698-063,77,STAFFORD ST,2,6000.0,1092.0,...,08275 0343,1,10,ONE FAMILY,False,12.464587,2024,7,237.179487,1.383547
1,2,9,3,3.0,121-698-062,73,STAFFORD ST,2,6000.0,936.0,...,07948-0001,1,10,ONE FAMILY,False,12.245298,2022,4,222.222222,1.081643
2,3,12,3,6.0,144-698-066,61,STAFFORD ST,2,6000.0,1111.0,...,08197-0077,1,10,ONE FAMILY,False,11.736077,2023,12,112.511251,0.842318
3,5,25,3,6.0,144-698-053,211,NEWINGTON AVE,2,5040.0,1684.0,...,07701-0245,1,10,ONE FAMILY,False,12.083911,2021,1,105.106888,0.894391
4,7,29,3,3.0,144-698-049,18,BRISTOL ST,2,6000.0,900.0,...,07834-0299,1,10,ONE FAMILY,False,12.144203,2021,9,208.888889,1.101347

In [7]:
# Remove identifier and text columns that do not contribute to analytical modeling
df = df.drop(columns=[
    "OBJECTID",
    "PropertyID",
    "ParcelID",
    "OwnerName",
    "PrimaryGrantor",
    "LegalReference",
    "LocationStreetName"
], errors="ignore")

df.head()

,xrCompositeLandUseID,xrBuildingTypeID,LocationStartNumber,StreetNameAndWay,xrPrimaryNeighborhoodID,LandSF,TotalFinishedArea,LivingUnits,OwnerLastName,SaleDate,...,TotalAppraisedValue,xrSalesValidityID,xrDeedID,AssrLandUse,WasZeroPrice,LogSalePrice,SaleYear,SaleMonth,PricePerSqft,AppraisalRatio
0,3,6.0,77,STAFFORD ST,2,6000.0,1092.0,1.0,WRIGHT,2024-07-01 00:00:00+00:00,...,187200,1,10,ONE FAMILY,False,12.464587,2024,7,237.179487,1.383547
1,3,3.0,73,STAFFORD ST,2,6000.0,936.0,1.0,SANTANA,2022-04-26 00:00:00+00:00,...,192300,1,10,ONE FAMILY,False,12.245298,2022,4,222.222222,1.081643
2,3,6.0,61,STAFFORD ST,2,6000.0,1111.0,1.0,MARTINEZ,2023-12-22 00:00:00+00:00,...,148400,1,10,ONE FAMILY,False,11.736077,2023,12,112.511251,0.842318
3,3,6.0,211,NEWINGTON AVE,2,5040.0,1684.0,1.0,CAHUANA FLORES,2021-01-11 00:00:00+00:00,...,197900,1,10,ONE FAMILY,False,12.083911,2021,1,105.106888,0.894391
4,3,3.0,18,BRISTOL ST,2,6000.0,900.0,1.0,NEGRON,2021-09-21 00:00:00+00:00,...,170700,1,10,ONE FAMILY,False,12.144203,2021,9,208.888889,1.101347

In [9]:
# Convert categorical land use type into numeric codes
df["AssrLandUse"] = df["AssrLandUse"].astype("category").cat.codes

df.head()

,xrCompositeLandUseID,xrBuildingTypeID,LocationStartNumber,StreetNameAndWay,xrPrimaryNeighborhoodID,LandSF,TotalFinishedArea,LivingUnits,OwnerLastName,SaleDate,...,TotalAppraisedValue,xrSalesValidityID,xrDeedID,AssrLandUse,WasZeroPrice,LogSalePrice,SaleYear,SaleMonth,PricePerSqft,AppraisalRatio
0,3,6.0,77,STAFFORD ST,2,6000.0,1092.0,1.0,WRIGHT,2024-07-01 00:00:00+00:00,...,187200,1,10,5,False,12.464587,2024,7,237.179487,1.383547
1,3,3.0,73,STAFFORD ST,2,6000.0,936.0,1.0,SANTANA,2022-04-26 00:00:00+00:00,...,192300,1,10,5,False,12.245298,2022,4,222.222222,1.081643
2,3,6.0,61,STAFFORD ST,2,6000.0,1111.0,1.0,MARTINEZ,2023-12-22 00:00:00+00:00,...,148400,1,10,5,False,11.736077,2023,12,112.511251,0.842318
3,3,6.0,211,NEWINGTON AVE,2,5040.0,1684.0,1.0,CAHUANA FLORES,2021-01-11 00:00:00+00:00,...,197900,1,10,5,False,12.083911,2021,1,105.106888,0.894391
4,3,3.0,18,BRISTOL ST,2,6000.0,900.0,1.0,NEGRON,2021-09-21 00:00:00+00:00,...,170700,1,10,5,False,12.144203,2021,9,208.888889,1.101347

In [11]:
# Compute correlation between features and target variable
corr = df.corr(numeric_only=True)

corr["LogSalePrice"].sort_values(ascending=False)

LogSalePrice               1.000000
SalePrice                  0.584656
AppraisalRatio             0.574682
PricePerSqft               0.563352
xrSalesValidityID          0.155017
xrBuildingTypeID           0.135466
xrDeedID                   0.094025
xrPrimaryNeighborhoodID    0.067735
SaleMonth                  0.048053
LandSF                     0.045119
SaleYear                   0.038337
xrCompositeLandUseID       0.007885
TotalAppraisedValue        0.003098
LocationStartNumber       -0.033663
LivingUnits               -0.039853
TotalFinishedArea         -0.051793
AssrLandUse               -0.112302
WasZeroPrice                    NaN
Name: LogSalePrice, dtype: float64

In [13]:
# Select features strongly correlated with LogSalePrice
important = corr["LogSalePrice"].abs() > 0.2

selected_features = corr.columns[important]

df_selected = df[selected_features]

df_selected.head()

   SalePrice  LogSalePrice  PricePerSqft  AppraisalRatio
0   259000.0     12.464587    237.179487        1.383547
1   208000.0     12.245298    222.222222        1.081643
2   125000.0     11.736077    112.511251        0.842318
3   177000.0     12.083911    105.106888        0.894391
4   188000.0     12.144203    208.888889        1.101347

In [15]:
# Display final selected features for modeling
print("Selected Features:")
print(selected_features)

Selected Features:
Index(['SalePrice', 'LogSalePrice', 'PricePerSqft', 'AppraisalRatio'], dtype='str')

In [17]:
df.head()

,xrCompositeLandUseID,xrBuildingTypeID,LocationStartNumber,StreetNameAndWay,xrPrimaryNeighborhoodID,LandSF,TotalFinishedArea,LivingUnits,OwnerLastName,SaleDate,...,TotalAppraisedValue,xrSalesValidityID,xrDeedID,AssrLandUse,WasZeroPrice,LogSalePrice,SaleYear,SaleMonth,PricePerSqft,AppraisalRatio
0,3,6.0,77,STAFFORD ST,2,6000.0,1092.0,1.0,WRIGHT,2024-07-01 00:00:00+00:00,...,187200,1,10,5,False,12.464587,2024,7,237.179487,1.383547
1,3,3.0,73,STAFFORD ST,2,6000.0,936.0,1.0,SANTANA,2022-04-26 00:00:00+00:00,...,192300,1,10,5,False,12.245298,2022,4,222.222222,1.081643
2,3,6.0,61,STAFFORD ST,2,6000.0,1111.0,1.0,MARTINEZ,2023-12-22 00:00:00+00:00,...,148400,1,10,5,False,11.736077,2023,12,112.511251,0.842318
3,3,6.0,211,NEWINGTON AVE,2,5040.0,1684.0,1.0,CAHUANA FLORES,2021-01-11 00:00:00+00:00,...,197900,1,10,5,False,12.083911,2021,1,105.106888,0.894391
4,3,3.0,18,BRISTOL ST,2,6000.0,900.0,1.0,NEGRON,2021-09-21 00:00:00+00:00,...,170700,1,10,5,False,12.144203,2021,9,208.888889,1.101347

In [19]:
df.to_csv("feature_engineered_dataset.csv", index=False)